server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进Eureka服务器的微服务名

  cloud:
    config:
      server:
        git:
          uri: https://github.com/BiXingyu/springcloud-config.git
          search-paths:
            - springcloud-config
          username: BiXingyu
          password: Abcd1234@@@@@
          default-label: main
          skip-ssl-validation: true
        #读取分支

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka