server:
  port: 8004
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 192.168.36.101:2181


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3307/dbtest1?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: abc123
    druid:
      validation-query: select 1