server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment-routh #路由的ID,没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**  #断言，路径相匹配的进行路由
            - After=2023-01-01T15:05:59.892+08:00[Asia/Shanghai]
#            - Cookie=username,bxy

#        - id: payment_routh2 #payment-routh #路由的ID,没有固定规则但要求唯一，建议配合服务名
#          uri: lb://CLOUD-PAYMENT-SERVICE  #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/hystrix/ok/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
    register-with-eureka: true
    fetch-registry: true